---
- :html_id: brisson-tracy
  :first_name: Tracy
  :last_name: Brisson
  :company: The Opportunities Project
  :description: Tracy Brisson is the founder and CEO of The Opportunities Project,
    a national talent development, coaching, and recruitment consulting agency launched
    in 2010. Through speaking engagements, workshops, and coaching, Tracy has helped
    more than 1,000 individuals reach career happiness and helped organizations hire
    500+ new employees. She is the author of Create Your Own Opportunities and Confessions
    of a Teacher Recruiter and her career advice regularly appears in media outlets
    such as Mashable and CBS Moneywatch. An alumna of Syracuse University, New York
    University, and Teach For America, Tracy now lives in Savannah. 
  :photo: /images/speakers/2013/BrissonTracy.jpg
- :html_id: clagett-bob
  :first_name: Bob
  :last_name: Clagett
  :company: Dell, Inc.
  :description: Bob Clagett likes to make stuff...  He's a software engineer by day, but the rest of the time, he builds, fixes, hacks, explores, and plays with his four amazing little adventurers. He's a musician and maker, husband and father, and blogs about all of his projects at <a href="http://iliketomakestuff.com">iliketomakestuff.com</a>.
  :photo: /images/speakers/2013/ClagettBob.jpg
- :html_id: drew-amy
  :first_name: Amy
  :last_name: Drew
  :company: Music Teacher
  :description: Amy Drew was born in Western New York and earned a BA in Music Education
    at Nazareth College of Rochester.  Her career as a teacher began in 1998.  Two
    years later, West Virginia became her home.  Summers were spent guiding white
    water raft trips and waitressing.  After teaching in public and private schools,
    Amy traded lesson plans for a backpack and hiked the Appalachian Trail from Georgia
    to Maine.  2,200 miles later, she exchanged her backpack for a van and headed
    west.  Eventually, Amy landed in Savannah where she owns a school of music.
  :photo: /images/speakers/2013/DrewAmy.jpg
- :html_id: duane-ja-nae
  :first_name: Ja-Nae
  :last_name: Duane
  :company: Revolution Institute
  :description: One woman revolution Ja-Naé Duane is a social scientist, artist, and
    author. Her unwavering commitment to improving the quality of life for the global
    community garnered Ja-Naé a nomination as one of New England’s Most Innovative
    Leaders of 2007. Currently a faculty member at Northeastern University and Clark
    University, Ja-Naé’s latest book, How to Create a Revolution, focuses on the ability
    to create impactful change through social influence
  :photo: /images/speakers/2013/DuaneJa-Nae.jpg
- :html_id: garnier-marc
  :first_name: Marc
  :last_name: Garnier
  :company: Saraz Handpans
  :description: A musician for more than 20 years and a fan of exotic folk instruments, Marc Garnier discovered a new type of steel drum in 2009 called a handpan. Marc purchased his first in 2011 and an obsession quickly developed. As he learned that the highest quality handpans were difficult to purchase, Marc set out to build his own and in the process, founded Saraz Musical Instruments in 2012.
  :photo: /images/speakers/2013/GarnierMarc.jpg  
- :html_id: gerards-chris
  :first_name: Chris
  :last_name: Gerards
  :company: City of Savannah
  :description: Board Certified Master Arborist and Municipal Specialist Chris CM
    Gerards has been involved in arboriculture for 30+ years. Chris was born in the
    Netherlands, moved to the United States in 1978 and arrived in Savannah two years
    ago. As the Senior Tree Maintenance Worker for the City of Savannah, Chris participates
    in the renovation of city squares, maintains trees in Forsyth Park, manages the
    City’s tree-planting program and has pruned 2,000+ Savannah trees in the process.
    The father of two wonderful sons, Roland and Alexander, Chris likes to sail and
    read.
  :photo: /images/speakers/2013/GerardsChris.jpg
- :html_id: haas-robert
  :first_name: Robert
  :last_name: Haas
  :company: Congregation Mickve Israel
  :description: Congregation Mickve Israel’s new rabbi, Robert Haas, came to Savannah
    in 2012 by way of Texas, Israel and Africa.  He was born in McAllen, Texas, graduated
    from the University of Texas at Austin, and taught in Houston’s public schools.  He
    then lived and studied in Israel, entered rabbinical school and was ordained in
    the first Reform Rabbinical Class on the West Coast. After serving as a rabbi
    in Dallas and Houston, Robert went to Africa in 2011 as a volunteer with the American
    Jewish World Service.  He now serves as the rabbi for the third oldest Jewish
    Congregation in America.
  :photo: /images/speakers/2013/HaasRobert.jpg
- :html_id: killingsworth-catherine
  :first_name: Catherine
  :last_name: Killingsworth
  :company: DEEP
  :description: Catherine Killingsworth is the executive director of Deep, a nonprofit
    that provides after-school creative writing workshops in Savannah area public
    schools (www.deepkids.com). She earned a degree in English from Yale University
    and has studied education and literature abroad on various fellowships. She is
    the author of The Cure for IDK, a book of writing lesson plans, and she blogs
    about writing and education at thatwritinglady.com. 
  :photo: /images/speakers/2013/KillingsworthCatherine.jpg
- :html_id: lake-dave
  :first_name: Dave
  :last_name: Lake
  :company: Armstrong Atlantic State University
  :description: Dave Lake has a PhD in physiology, is a licensed physical therapist
    and has lectured at Armstrong Atlantic State University on obesity and metabolic
    syndrome for a number of years.  He recently became interested in local/sustainable
    agriculture, leading two panel discussions on the topic and presenting a lecture
    entitled “Is Our food Killing Us”. As the founding department head, and now a
    professor in Armstrong’s physical therapy program, Dave has presented more than
    120 papers at national and international symposiums and has authored 15 peer-reviewed
    publications.
  :photo: /images/speakers/2013/LakeDave.jpg
- :html_id: little-paul
  :first_name: Paul
  :last_name: Little
  :company: First African Baptist Church
  :description: As a community leader, Paul Little partners with organizations to
    improve the quality of life for others. He serves as youth minister at First African
    Baptist Church in Savannah and is an active member with numerous organizations
    including the Board of Education's Community Engagement Task Force, Memorial Health's
    Violence Intervention Program, and Dismas Charities' Community Relations Board.
    With a message that resonates with many, Paul speaks locally and nationally at
    public schools, on college campuses, and at churches of all denominations. He
    is married to his best friend and the love of his life, Natalie Little.
  :photo: /images/speakers/2013/LittlePaul.jpg
- :html_id: nichols-josh
  :first_name: Josh
  :last_name: Nichols
  :company: Self-Employed
  :description: A professional software developer by trade, Josh Nichols has written
    and contributed to a number of widely used open source projects. Originally from
    New Hampshire, Josh worked in Boston before finding himself in Savannah. Today
    Josh maintains an active role within the developer community, writing comprehensive
    blog posts, organizing regular meetups, and presenting at conferences.  Content
    with the quality and pace of life in Savannah, Josh enjoys reading, slaying dragons,
    hackey sack, and making up words.
  :photo: /images/speakers/2013/NicholsJosh.jpg
- :html_id: platt-juwan
  :first_name: Juwan Platt 
  :last_name: and Donovan Woods
  :company: Vizionary Minds | Creative Club
  :description: Budding film director and co-founder of Vizionary Mindz | Creative Club , Donovan Woods is a youthful entrepreneur with a strong dedication and interest in to upping the ante in Savannah's emerging creative scene. Community, art, and milkshakes are his joys of life. A student of photography and videography, Juwan Platt is a youthful sprite with the soul of a man 4 times his age. A visual storyteller, he enjoys capturing people in their natural element allowing life to be their only stylist. Juwan is a lover of travel, good food and well-fitting pants.
  :photo: /images/speakers/2013/DonovanAndJuwan.jpg
- :html_id: siceloff-mary
  :first_name: Mary
  :last_name: Siceloff
  :company: Hunter Maclean
  :description: Mary Siceloff grew up on St. Helena Island, S.C. where her father
    ran Penn Center. After stints in Afghanistan and Atlanta, she moved to Los Angeles
    and worked in film and television production for way too long.  She finally achieved
    escape velocity, moving into web development, marketing, and various and sundry
    offshoots of both.  She moved back to the South in 2006 and currently handles
    business development for HunterMaclean. She has never been good at math.
  :photo: /images/speakers/2013/SiceloffMary.jpg
- :html_id: wilson-murray
  :first_name: Murray
  :last_name: Wilson
  :company: tps Consulting LLC
  :description: Murray Wilson has consulted in the professional broadcast television
    industry for 25 years. Heavily involved in the industry’s transition from analog
    to digital, he has played an integral role in the operational development and
    deployment of some of the largest multi-channel digital broadcast facilities in
    the world. Born and educated in England, Murray has lived in the United States
    since 1979.  He now lives in Savannah, is president of tps Consulting, and continues
    his life-long fascination in all things technical.
  :photo: /images/speakers/2013/WilsonMurray.jpg
